### ISSUE TITLE
mini-eNAEP: different capitalization in file system and javascript files

### ISSUE THREAD

**Issue by garyfeng** [NAEPDEV/2021-tutorial-on-the-web#1]
The initial version we received from 2019 does not work for GitHub Page because sloppy code and folder naming conventions. It appears the original version was developed in Windows where the path is not case-sensitive; but github page is. I made the following changes as a quick and dirty fix:

- changed folder such as "Script" to `script`, `Scratchwork` to `scratchwork`
- then `Content` and `content` are both used. Just have to stick with one. I did a global search-replace. 
- `/app/en` should be changed to `app/EN` in `index.html`
- `cur_draw_scratchwork.cur` should be `Cur_Draw_Scratchwork.cur` in some js files; or rename the cursor file. I chose to edit the code.

There may have been other similar changes; see the commit history.

**Comment by coreymcg** [comment]
As far as I can tell this has been fixed. For consistency, I've renamed the EN and ES to lowercase in #9.
