### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by coreymcg** [NAEPDEV/2021-tutorial-on-the-web#13]
- [ ] Overview
- [ ] Dev setup
- [ ] Bookmaps
- [ ] Config / URL params
- [ ] Video autoplay

**Comment by garyfeng** [comment]
- [ ] Instructions on how to record and process videos
- [ ] Instruction on how to do subrip subtitle

**Comment by coreymcg** [comment]
Closing this as we've covered these topics in both 123afeb and f253473,
