### ISSUE TITLE
Audio muted for direct access

### ISSUE THREAD

**Issue by garyfeng** [NAEPDEV/2021-tutorial-on-the-web#16]
Per Chrome policy https://www.chromium.org/audio-video/autoplay, autoplayed video cannot have audio until user interacts with the webpage. 

The tutorial plays correctly if the user accesses the tutorial via the launching page, https://naepdev.github.io/2021-tutorial-on-the-web, as the user will need to click on one of the tutorials, hence completing the first interaction. 

If the user directly access a tutorial module (e.g., via a bookmark), e.g., https://naepdev.github.io/2021-tutorial-on-the-web/app/en/main.html?subject=SocialSciences8, the audio is muted until you have some interaction with the page, e.g., clicking on the screen somewhere. 

Would be nice if we detect the direct access and display a message of sort to elicit an user action, so that the audio plays normally. This could be an info pop-up panel letting the user know the correct launching URL.

**Comment by coreymcg** [comment]
I've added autoplay detection. 

4bb7607

If autoplay is enabled then it will automatically play the captivate content. If not, clicking on the play button in the middle of the screen will start it. I feel as though this covers this edge case well enough without spending too much more time on it.

During development the autoplay can be permanently enabled in the site settings (Lock or Info icon in address bar > Site Settings > Sound > Enabled).

Let me know if this works well from your end and I will merge in the change.

**Comment by apolanco-ets** [comment]
As far as I can tell, your fix worked - @coreymcg . We can probably close this ticket, unless you still wanted to investigate modifying the local Captivate install to prevent needing to do this post-export fix.

**Comment by garyfeng** [comment]
closing

**Comment by coreymcg** [comment]
Merged into master via f5781ce
