### ISSUE TITLE
tutorial loop-back: 404 for social studies

### ISSUE THREAD

**Issue by garyfeng** [NAEPDEV/2021-tutorial-on-the-web#2]
Testing the social study grade 8 tutorial, commit ee26007

Autoplayed to the end, and got a 404 error when the URL got routed to https://naepdev.github.io/2021-tutorial-on-the-web/app/EN/tutorials/Intro-SS/main.html?subject=SocialSciences8&module=1

**Comment by garyfeng** [comment]
same result with Reading.

**Comment by garyfeng** [comment]
the redirect URL should have been https://naepdev.github.io/2021-tutorial-on-the-web/app/EN/main.html?subject=Reading8&module=1, as opposed to https://naepdev.github.io/2021-tutorial-on-the-web/app/EN/tutorials/Intro-SS/main.html?subject=SocialSciences8&module=1

**Comment by coreymcg** [comment]
Fixed by GH-8 & GH-6
